### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by lfcgomes** [perry-mitchell/webdav-fs#11]
Are you considering to include update file features? It would be great to rename a file, or even change its parent, for instance.

It's possible to get more info when listing a directory content? Mimetype, modification date (maybe), etc etc. Actually we only have access to file name.
The same goes to `stat` function.

**Comment by perry-mitchell** [comment]
There are some other parameters provided by webdav's PROPFIND method, but I didn't see a whole lot of useful information. I believe I already return MIME currently.

Renaming a file etc. could definitely be added. You can always make a PR, otherwise it may be a short period before I can add it myself.

**Comment by perry-mitchell** [comment]
#12 addresses moving files, if possible.

**Comment by lfcgomes** [comment]
I think I'm going to need this, so I definitely can take a look on that :)

**Comment by stevenkaspar** [comment]
Hey guys,
I didn't do a pull request but I have been able to add renameFile, duplicateFile, moveFile, copyFile **functionality**.  The WebDav server I am using doesn't allow MOVE, and UNLOCK methods so this is the way I have to go anyway

`
            /* getFile => putFile to same location with date_string added on //*/
			duplicateFile: function(/* filename[, encoding], callback */) {
				var args = Array.prototype.slice.call(arguments),
					argc = args.length;
				if (argc <= 1) {
					throw new Error("Invalid number of arguments");
				}
				var path = args[0],
					encoding = (typeof args[1] === "string") ? args[1] : undefined,
					callback = function() {};
				if (typeof args[1] === "function") {
					callback = args[1];
				} else if (argc >= 3 && typeof args[2] === "function") {
					callback = args[2];
				}
				client.getFile(endpoint, path, encoding).then(function(data) {
                    var date = new Date();
                    date = (date.getMonth() + 1) + '_' + date.getDate() + '_' +  date.getFullYear() + '_' +  date.getHours() + '_' +  date.getMinutes() + '_' +  date.getMilliseconds();
                    var new_name = path.split('.').slice(0,-1) + '_' + date + '.' + path.split('.').slice(-1);
                    
                    client.putFile(endpoint, new_name, data, encoding).then(
						function() {
							executeCallbackAsync(callback, [null]);
						},
						function(err) {
							executeCallbackAsync(callback, [err]);
						}
					);
                },
                function(err) {
                    executeCallbackAsync(callback, [err, null]);
                });
			},
            /* getFile => putFile to args[1] path //*/
			copyFile: function(/* filename[, encoding], callback */) {
				var args = Array.prototype.slice.call(arguments),
					argc = args.length;
				if (argc <= 2) {
					throw new Error("Invalid number of arguments");
				}
				var path = args[0],
                    new_path = args[1],
					encoding = (typeof args[2] === "string") ? args[2] : undefined,
					callback = function() {};
				if (typeof args[2] === "function") {
					callback = args[2];
				} else if (argc >= 4 && typeof args[3] === "function") {
					callback = args[3];
				}
				client.getFile(endpoint, path, encoding).then(function(data) {
                    client.putFile(endpoint, new_path, data, encoding).then(function() {
                        executeCallbackAsync(callback, [null]);
                    }).catch(function(err) {
                        executeCallbackAsync(callback, [err]);
                    });
                },
                function(err) {
                    executeCallbackAsync(callback, [err, null]);
                });
			},

            /* getFile => putFile to same location with args[1] name => deletePath of args[0] //*/
			renameFile: function(/* filename[, encoding], callback */) {
				var args = Array.prototype.slice.call(arguments),
					argc = args.length;
				if (argc <= 2) {
					throw new Error("Invalid number of arguments");
				}
				var path = args[0],
                    new_name = args[0].split('/').slice(0,-1).join('/') + '/' + args[1],
					encoding = (typeof args[2] === "string") ? args[2] : undefined,
					callback = function() {};
				if (typeof args[2] === "function") {
					callback = args[2];
				} else if (argc >= 4 && typeof args[3] === "function") {
					callback = args[3];
				}
				client.getFile(endpoint, path, encoding).then(function(data) {
                    client.putFile(endpoint, new_name, data, encoding).then(function() {
                        client.deletePath(endpoint, path).then(function() {
                            executeCallbackAsync(callback, [null]);
                        });
                    }).catch(function(err) {
                        executeCallbackAsync(callback, [err]);
                    });
                },
                function(err) {
                    executeCallbackAsync(callback, [err, null]);
                });
			},

            /* getFile => putFile in new args[1] path => deletePath of args[0] //*/
			moveFile: function(/* filename[, encoding], callback */) {
				var args = Array.prototype.slice.call(arguments),
					argc = args.length;
				if (argc <= 2) {
					throw new Error("Invalid number of arguments");
				}
				var path = args[0],
                    new_path = args[1],
					encoding = (typeof args[2] === "string") ? args[2] : undefined,
					callback = function() {};
				if (typeof args[2] === "function") {
					callback = args[2];
				} else if (argc >= 4 && typeof args[3] === "function") {
					callback = args[3];
				}
				client.getFile(endpoint, path, encoding).then(function(data) {
                    client.putFile(endpoint, new_path, data, encoding).then(function() {
                        client.deletePath(endpoint, path).then(function() {
                            executeCallbackAsync(callback, [null]);
                        });
                    }).catch(function(err) {
                        executeCallbackAsync(callback, [err]);
                    });
                },
                function(err) {
                    executeCallbackAsync(callback, [err, null]);
                });
			}`

**Comment by lfcgomes** [comment]
Great! Thanks @stevenkaspar . @perry-mitchell If t's ok for you  I'm going to add this to my PR also.

**Comment by stevenkaspar** [comment]
@lfcgomes some more additions. These will recursively copy, rename, move directories, and return directory structure

    getFullDir: function(auth, path) {
			path = sanitiseRemotePath(path);
			if (path.length <= 0) {
				path = "/";
			}
            var self = this;
			return new Promise(function(resolve, reject){
                fetch(auth.url + path, {
                    method: "PROPFIND",
                    headers: {
                        Depth: '1'
                    }
                }).then(function(res) {
                    if([200,201,207].indexOf(res.status) == -1){
                        console.log(res.status + ' ' + res.statusText + '('+path+')');
                        reject(res.status + ' ' + res.statusText + '('+path+')');
                    }
                    else {
                        return res.text();
                    }

                }).then(function(body) {
                    var parser = new xml2js.Parser();
                    parser.parseString(body, function (err, result) {
                        if (err) {
                            console.log(err);
                        } 
                        else {
                            var bro_results = processDirectoryResult(path, result);
                            return Promise.all(
                                bro_results.map(function(res, index){
                                    return new Promise(function(resolve, reject){
                                        if(res.type === 'directory'){
                                            self.getFullDir(auth, res.filename).then(function(response){
                                                bro_results[index].children = response;
                                                resolve();
                                            });
                                        }
                                        else {
                                            resolve();
                                        }
                                    })
                                })
                            ).then(function(promise_array){
                                resolve(bro_results);
                            })
                        }
                    });
                });
            })
		},

		copyDir: function(auth, path, new_path) {
			path = sanitiseRemotePath(path);
			new_path = sanitiseRemotePath(new_path);
			if (path.length <= 0) {
				path = "/";
			}
			if (new_path.length <= 0) {
				new_path = "/";
			}
            var self = this;
			return new Promise(function(resolve, reject){
                fetch(auth.url + path, {
                    method: "PROPFIND",
                    headers: {
                        Depth: '1'
                    }
                }).then(function(res) {
                    if([200,201,207].indexOf(res.status) == -1){
                        console.log(res.status + ' ' + res.statusText + '('+path+')');
                        reject(res.status + ' ' + res.statusText + '('+path+')');
                    }
                    else {
                        return res.text();
                    }

                }).then(function(body) {
                    var parser = new xml2js.Parser();
                    parser.parseString(body, function (err, result) {
                        if (err) {
                            console.log(err);
                        } 
                        else {
                            var bro_results = processDirectoryResult(path, result);
                            return Promise.all(
                                bro_results.map(function(res, index){
                                    return new Promise(function(resolve, reject){
                                        if(res.type === 'directory'){
                                            self.putDir(auth, new_path+'/'+res.basename).then(function(){
                                                self.copyDir(auth, res.filename, new_path+'/'+res.basename).then(function(response){
                                                    bro_results[index].children = response;                                                    
                                                    resolve();
                                                });
                                            })
                                        }
                                        else {
                                            self.getFile(auth, res.filename).then(function(data){
                                                self.putFile(auth, new_path + '/' + res.basename, data).then(function(response){
                                                    resolve();
                                                })
                                            })
                                        }
                                    })
                                })
                            ).then(function(promise_array){
                                resolve(bro_results);
                            })
                        }
                    });
                });
            })
		},

		moveDir: function(auth, path, new_path) {
			path = sanitiseRemotePath(path);
			new_path = sanitiseRemotePath(new_path);
			if (path.length <= 0) {
				path = "/";
			}
			if (new_path.length <= 0) {
				new_path = "/";
			}
            var self = this;
			return new Promise(function(resolve, reject){
                fetch(auth.url + path, {
                    method: "PROPFIND",
                    headers: {
                        Depth: '1'
                    }
                }).then(function(res) {
                    if([200,201,207].indexOf(res.status) == -1){
                        console.log(res.status + ' ' + res.statusText + '('+path+')');
                        reject(res.status + ' ' + res.statusText + '('+path+')');
                    }
                    else {
                        return res.text();
                    }

                }).then(function(body) {
                    var parser = new xml2js.Parser();
                    parser.parseString(body, function (err, result) {
                        if (err) {
                            console.log(err);
                        } 
                        else {
                            var bro_results = processDirectoryResult(path, result);
                            return Promise.all(
                                bro_results.map(function(res, index){
                                    return new Promise(function(resolve, reject){
                                        if(res.type === 'directory'){
                                            self.putDir(auth, new_path+'/'+res.basename).then(function(){
                                                self.moveDir(auth, res.filename, new_path+'/'+res.basename).then(function(response){
                                                    bro_results[index].children = response;                                                    
                                                    resolve();
                                                });
                                            })
                                        }
                                        else {
                                            self.getFile(auth, res.filename).then(function(data){
                                                self.putFile(auth, new_path + '/' + res.basename, data).then(function(response){
                                                    resolve();
                                                })
                                            })
                                        }
                                    })
                                })
                            ).then(function(promise_array){
                                self.deletePath(auth, path).then(function(){
                                    resolve(bro_results);
                                })
                            })
                        }
                    });
                });
            })
		},

		renameDir: function(auth, path, new_name ) {
            var new_path = '';
            
			path = sanitiseRemotePath(path);
            if(new_name) new_path = path.split('/').slice(0,-1).join('/') + '/' + new_name;
			new_path = sanitiseRemotePath(new_path);
            
            var self = this;
            return new Promise(function(resolve, reject){
                
                self.moveDir(auth, path, new_path).then(function(results){
                    resolve(results);
                })
                
            });
		},

		duplicateDir: function(auth, path) {
            
            var date = new Date();
            date = (date.getMonth() + 1) + '_' + date.getDate() + '_' +  date.getFullYear() + '_' +  date.getHours() + '_' +  date.getMinutes() + '_' +  date.getMilliseconds();
            var new_path = path.split('/').slice(0,-1).join('/') + '/' + path.split('/').slice(-1) + '_' + date;
            
			path = sanitiseRemotePath(path);
			new_path = sanitiseRemotePath(new_path);
            
            var self = this;
            return new Promise(function(resolve, reject){
                
                self.copyDir(auth, path, new_path).then(function(results){
                    resolve(results);
                })
                
            });
		}

called from index.js using

			duplicateDir: function(path, callback) {
				client.duplicateDir(endpoint, path).then(function(dirData) {
                    (callback)(null, dirData);
                })
                .catch(function(err) {
                    (callback)(err, null);
                });
			}

**Comment by perry-mitchell** [comment]
Thanks for all the thought guys!

@stevenkaspar Having the code in an issue like this is a bit tedious - please place it in a PR in the future, as there's no use in me copy-pasting it from here.

**Comment by stevenkaspar** [comment]
Yea sorry about that. I figured it would be easier for @lfcgomes that way so he could just include it in his PR

**Comment by lfcgomes** [comment]
@perry-mitchell @stevenkaspar guys, regarding to your code, did you try to operate (copy, rename, get file, etc) a file that is not a plain text? I mean, a pdf for instance.

I'm trying to get everything together but I cannot do any operation with any file that is not a .txt. Am I missing any setup or flag on the encoding?

**Comment by stevenkaspar** [comment]
I was doing my development on php files and I just tested a pdf. I would think the file extension shouldn't matter unless your WebDav is configured differently to not allow it. It's all just 1s and 0s with a different file name, so file extension shouldn't matter

**Comment by lfcgomes** [comment]
php files work for me too. pdf, docx or png files don't :\

**Comment by perry-mitchell** [comment]
Strange. I'll run another test this weekend, but the tests cover binary transfer.

Are you using the encoding argument? Please attach a code sample.

**Comment by perry-mitchell** [comment]
Have made a new issue for writing binary files ( #14 ) - please follow that if you're having troubles.

**Comment by lfcgomes** [comment]
Guys, I left in #14 two sample of code to get a file (a pdf) from my own cloud server.

**Comment by ccoenen** [comment]
Thanks for the code @stevenkaspar! Any chance of getting `renameDir` into master?

**Comment by perry-mitchell** [comment]
@lfcgomes @ccoenen This feature will be added by the #17 MR.
