### ISSUE TITLE
Unify indentation

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-fs#20]
Code has different tabs indentation making it difficult to read. Unify it to standard two spaces.

**Comment by perry-mitchell** [comment]
Indentation standard is 4 spaces. This should be unified.

**Comment by piranna** [comment]
As far as I have seen the standard on Node.js projects are two spaces... Anyway, as far that it's uniform for all the project code, it's ok for me.

**Comment by bojan88** [comment]
Hey @perry-mitchell I would like to contribute. @piranna is right, most of the node projects use 2 spaces indentation as well as node core. Current indentation is mixed (tabs and spaces). I would like to fix that, but my question for you is will you accept 2 spaces indentation?

**Comment by perry-mitchell** [comment]
@bojan88 The common indenting for JS, that I've seen, is 4 spaces.. and as NodeJS is JavaScript, I see no reason to change it. This is of course a stylistic preference, and one which I'd prefer to keep in my projects. I do agree with the necessity for consistency, however, so anything differing from the 4 spaces should be updated.

I very much agree with many of Crockford's points: http://javascript.crockford.com/code.html

I don't want to discourage contributions, though I feel these stylistic points should be left to the maintainer as they often are..

**Comment by piranna** [comment]
Ok, now the code is readable ;-) Thank you! :-)
