### ISSUE TITLE
Use async API

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-fs#22]
Use callbacks or already being used promises in the `client` module instead of throwing errors on failure.

**Comment by perry-mitchell** [comment]
I'm not sure what you're meaning here. Callbacks are used to be as close to the node FS api as possible. Returning promises is easy. Not sure if you had a certain piece of code in mind?

**Comment by piranna** [comment]
In fact I was thinking about `client.js` and more exactly [this](https://github.com/perry-mitchell/webdav-fs/blob/b15e141be5318002ee26667ab18f2531ee27c9fe/source/client.js#L29-L36), but was not aware it was being used on the promise so the exception is already captured... Did you have mind about moving the WebDAC client to an independent module dependency?

**Comment by perry-mitchell** [comment]
I think the entire lib is due for a refactor - hence the versioning - but that's coming.

This would form part of that, though the title is a bit misleading as the API is already async.

**Comment by piranna** [comment]
Yes, I'm sorry about the title, I haven't used the `fetch` object and the `throw` statement confused me. +1 to the refactor :-)

**Comment by perry-mitchell** [comment]
Hi @piranna - I'm going to close this issue as it's a little ambiguous. The entire API will be updated as of #36
