### ISSUE TITLE
Implement fs stream methods

### ISSUE THREAD

**Issue by piranna** [perry-mitchell/webdav-fs#23]
Add `fs.createReadStream()` and `fs.createWriteStream()` methods and the `ReadStream` and `WriteStream` classes. They could be used as building blocks for the other operations, too.

**Comment by ultimate-tester** [comment]
I created a pull request for the createReadStream, works for me providing the start and end parameters to basically create a partial request

**Comment by mickael-kerjean** [comment]
You rock!

**Comment by mickael-kerjean** [comment]
Hum, just looked at the newly merged code and it misses the point of using stream in the first place.

I would have assume using stream would reduce the memory footprint of the library which would be very helpfull when downloading large files but with the newly merged code, it won't help at all.

**Comment by ultimate-tester** [comment]
A newer, better version is on it's way that will make more sense and will use native streams. That one will do ranged requests as well so should keep the memory footprint low (it will not store the full data in memory). Also keep in mind that my change requires start+end parameters which enable you to specify what range you want to receive, so if you specify a range that's too large for you then that's on you. You can choose to download a smaller range. But again, a new and better version is on it's way.

**Comment by perry-mitchell** [comment]
@mickael-kerjean @ultimate-tester The updated readstream stuff is in master pending a later release.

**Comment by perry-mitchell** [comment]
`createReadStream` was made available in version `1.2.0`.. Thanks for all the help and input 👍

**Comment by piranna** [comment]
> createReadStream was made available in version 1.2.0.. Thanks for all the help and input

Great! :-D I'll try to take a look later to see if I can improve it ;-)
