### ISSUE TITLE
Unknown Problem

### ISSUE THREAD

**Issue by MCTaylor17** [perry-mitchell/webdav-fs#3]
I'm duplicating the example code exactly but I'm unable to interact with the remote server.  I'm not sure what the problem.  When attempting to read a directory, the err object returns `null` and contents is an empty array even though I'm certain there are sub-folders and files at that location.  Writing a file returns `Bad response: 409`.

The only difference I see is that I'm using HTTPS with a subdomain (eg `https://subdomain.domain.com`).

Any ideas what the problem might be?  Is it possible to test the connection somehow?

**Comment by perry-mitchell** [comment]
Hi,

That's very interesting.. I can't imagine why it'd fail. It could possibly have something to do with this line: `webDAVEndpoint.replace(/(https?:\/\/)/i, "$1" + username + ":" + password + "@") :`

I don't like how the current authentication is made, though I'm not terrible familiar with the authentication side of webdav.

Are you able to try over HTTP at all? Just to confirm that it is HTTPS that's causing the problem?

**Comment by perry-mitchell** [comment]
Closing this, please feel free to reopen if you still have the issue.
