### ISSUE TITLE
Getting 401 error when using wfs.readdir on Omni Sync Server (which is a webdav server)

### ISSUE THREAD

**Issue by anoopemacs** [perry-mitchell/webdav-fs#31]
https://tonicdev.com/anoopemacs/tonic-npm-webdav-fs

**Comment by anoopemacs** [comment]
I have narrowed down the problem to authentication sendImmediately being set to true when calling the request.
Is there a way to set sendImmediately to false?

**Comment by perry-mitchell** [comment]
I'm not sure what `sendImmediately` is, but it doesn't originate from webdav-fs. I've not tested Omni Sync Server. If you manage to find what the issue is it'd be great if you could submit a PR or even describe the solution here.

**Comment by anoopemacs** [comment]
The server required digest authentication to login, so not an issue with webdav-fs here.
Kindly close this issue
