### ISSUE TITLE
Cannot read binary files properly

### ISSUE THREAD

**Issue by monatis** [perry-mitchell/webdav-fs#33]
I can get any sort of file from the client then upload to OwnCloud server properly, but binary files get damaged when re-reading them from OwnCloud server.

I'm using the following code (and both the image saved onto the disk and the one sent to the browser are damaged). Am I doing something wrong or is it a known bug?

    app.get('/photos/:photo', function(req, res) {
      wfs.readFile('/' + req.params.photo, 'binary', function(err, image) {
        if(err) return res.sendStatus(404); 
        fs.writeFile(__dirname+'output.jpg', image);
        res.type('image/jpeg').send(image);
      });
    });

**Comment by perry-mitchell** [comment]
Thanks @monatis this is indeed a bug. Unsure why the binary tests didn't catch it, but over owncloud I can reproduce corrupted data when using readFile. I'm using the following code to reproduce:

```
    const fs = require("fs");
    const path = require("path");

    var wfs = require("./index.js")(
        "https://some-owncloud-server.com/remote.php/webdav/",
        "user",
        "password"
    );

    wfs.readFile("/picture.jpg", "binary", function(err, data) {
        if (err) {
            throw err;
        }
        fs.writeFileSync(path.resolve(__dirname, "./picture.jpg"), data);
    });
```

The image is corrupt and too large, so something is failing during reading.
