### ISSUE TITLE
please consider adding a CHANGELOG

### ISSUE THREAD

**Issue by ccoenen** [perry-mitchell/webdav-fs#35]
It's not obvious, what changed between versions right now. Sometimes, even the commit-messages are not immediately obvious for an outsider. Many Projects have something like a `CHANGELOG` file, that has a high-level view of changes between versions.

I would like to suggest adding such a changelog to this project.

**Comment by ccoenen** [comment]
relavant read that explains the importance far better than I could: http://keepachangelog.com/

**Comment by perry-mitchell** [comment]
Thanks @ccoenen, I've started adding changelogs to a few of my repos. This one could be next.

**Comment by perry-mitchell** [comment]
I've added a changelog with versions back to v0.6.0, which I feel is sufficient. Thanks for mentioning this issue.

**Comment by ccoenen** [comment]
Thank you for taking the time! :)
