### ISSUE TITLE
Propose new API

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-fs#36]
There's quite little benefit to following the basic structure of Node's `fs` API, and many improvements could be made if webdav-fs' were rewritten to:

 * allow for promises
 * more consistent function names

**Comment by piranna** [comment]
It's your library, but :-1:. Its name itself show that it follow the Node.js fs API. I don't think it's a bad idea to rewrite the code and use Promises and Sreams, but I would do it at a lower level layer, maybe in an internal class or also on its own module using it as dependency. My two cents

**Comment by perry-mitchell** [comment]
Well yes, my original intention was to follow the node API.. but I'm not going to tear it down if everyone thinks it's a terrible idea 😅.

That being said - why should this API stay like nodes just because of a similarity in the name? Does knowing the node API really make using this library that much easier or more practical? My opinion here is no.

Would users benefit from an intuitive interface that uses more modern response formats (or even both)? I believe so - moreover I'm not sure that people are even using this library for the fs similarities.

Anyhow.. that's my thinking. I'd like to make the library a bit more robust and overhauling the API would have fallen into that. I could keep both the current API and a better one, but that feels like overkill. It's a shame that someone has to wrap the library themselves to get better interfaces like promises.

**Comment by sallar** [comment]
I’d suggest sticking to nodejs API but also adding support for promises when there's no callback present. That’s how I’d want to use it IMHO

**Comment by perry-mitchell** [comment]
I've also started a poll on this: https://twitter.com/perry_mitchell/status/783967528699789312

**Comment by piranna** [comment]
Well, not just the name... :-P The Node.js `fs` API is somewhat standard and people are use to it, so there are other libraries that use a `fs`-like API like [memfs](https://www.npmjs.com/package/memfs) and [unionfs](https://www.npmjs.com/package/unionfs). This makes all of them easy to use, but more than that, they are interchangeable and swappable ones with others, and in fact being such a standard it would make it possible to [export any `fs`-like objects as a FUSE filesystem](https://github.com/mafintosh/fuse-bindings/issues/16).

In the end, the `fs` methods are just an API, so it doesn't matter the actual implementation. I find it ok to have a WebDAV client object using Promises and Streams that closely mimics the WebDAV specification and behaviour, and later to have a wrapper object that use that client object and export a `fs`-like API on top of it, and in fact I think it's the ideal solution, the only point is that I would put the lower level WebDAV client object in an independent module and split it from the one exporting the `fs`-like API (that by the name it would be this one).

**Comment by perry-mitchell** [comment]
@piranna 
> put the lower level WebDAV client object in an independent module and split it from the one exporting the fs-like API

I really like this idea. Having a module with all the bells and whistles that I'm looking for would be great, and webdav-fs could merely make use of that as a wrapper. The experience would be the same and there'd be no breaking changes.

> possible to export any fs-like objects as a FUSE filesystem

I started webdav-fuse because of my fascination with this.. I should really get back into that. It might prove easier once I've sorted this API issue out though.

**Comment by piranna** [comment]
> @piranna
> 
>     put the lower level WebDAV client object in an independent module and split it from the one exporting the fs-like API
> 
> I really like this idea. Having a module with all the bells and whistles that I'm looking for would be great, and webdav-fs could merely make use of that as a wrapper. The experience would be the same and there'd be no breaking changes.

Then we agree on that :-)


> possible to export any fs-like objects as a FUSE filesystem
> 
> I started webdav-fuse because of my fascination with this.. I should really get back into that. It might prove easier once I've sorted this API issue out though.

Do you have it somewhere? What advantages would have to do it directly that instead hook it using the `fs`-like API? I was thinking about doing a `fs-fuse` module that would translate any `fs`-like object in `FUSE` calls using `fuse-bindings` module, that's why I created that issue there...

**Comment by perry-mitchell** [comment]
Using WebDAV over fuse would of course allow you to write a mounting utility in node - allowing you to invoke other programs on the contents of a WebDAV account. I'd say it's more interesting in terms of experimentation rather that applicability. 

In that case it would be more advantageous to use a lower level WebDAV library rather than this fs module - commands like readdir require extra (costly) calls to detect file types, so using a hybrid API would be better in terms of performance for a fuse mount. 

It's in my account, though I don't remember the state of it - definitely not functional yet, but I may update it soon.

**Comment by perry-mitchell** [comment]
I've created a new repo for the core webdav functionality: https://github.com/perry-mitchell/webdav-client

Once it's ready, I will use it in webdav-fs for all the remote stuff. Thanks for everyone's input.

**Comment by perry-mitchell** [comment]
To close this, PR #37 integrates webdav-client for 1.0.0! The API will remain the same.

Thanks @piranna for the suggestion.

**Comment by piranna** [comment]
You are welcome :-) Remember, in case of doubt, split the project and modularize ;-)
