### ISSUE TITLE
Invalid URI error when password contains #

### ISSUE THREAD

**Issue by sandor93** [perry-mitchell/webdav-fs#39]
If the password contains html special chars e.g. # , the accessUrl will be malformed and invalid url error will be thrown. The error is still there even if I pass the password as an url encoded string.

Possible fix:
add "password = require('querystring').escape(password);"  before building up the accessURL
and "endpoint.password = require('querystring').unescape(password);" when saving the endpoint password

**Comment by perry-mitchell** [comment]
This is actually a bug in [webdav-client](https://github.com/perry-mitchell/webdav-client/): perry-mitchell/webdav-client#5

**Comment by perry-mitchell** [comment]
This has been fixed with 0.1.1 of webdav-client

**Comment by perry-mitchell** [comment]
Fixed and released as 1.0.0-rc2
