### ISSUE TITLE
What are these "d:whatever" selectors?

### ISSUE THREAD

**Issue by smolnikov** [perry-mitchell/webdav-fs#43]
I've got this result in webdav response:
```
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:"><response><href>/some/secret/url/</href>
<propstat><prop><creationdate>2017-04-03T09:37:02Z</creationdate>
<getlastmodified>Mon, 03 Apr 2017 09:37:02 GMT</getlastmodified>
<displayname>catalog_delta</displayname>
<getetag>1ff909964cc5f2a679103d4aa0540a62</getetag>
<resourcetype><collection/></resourcetype>
</prop>
<status>HTTP/1.1 200 OK</status>
</propstat>
</response>
<response><href>/some/secret/url/FullExport_03-27-2017.json</href>
<propstat><prop><creationdate>2017-03-28T12:31:48Z</creationdate>
<getlastmodified>Tue, 28 Mar 2017 12:31:48 GMT</getlastmodified>
<displayname>FullExport_03-27-2017.json</displayname>
<getcontentlength>16101266</getcontentlength>
<getcontenttype>application/json</getcontenttype>
<getetag>f2d6210e9d8c1c4f5aa5267264170907</getetag>
<resourcetype/></prop>
<status>HTTP/1.1 200 OK</status>
</propstat>
</response>
<response><href>/some/secret/url/DeltasFeed_since_04-02-2017.json</href>
<propstat><prop><creationdate>2017-04-03T09:39:35Z</creationdate>
<getlastmodified>Mon, 03 Apr 2017 09:39:35 GMT</getlastmodified>
<displayname>DeltasFeed_since_04-02-2017.json</displayname>
<getcontentlength>545552</getcontentlength>
<getcontenttype>application/json</getcontenttype>
<getetag>b89e88cf520ea77274977e4dd7dc9ecb</getetag>
<resourcetype/></prop>
<status>HTTP/1.1 200 OK</status>
</propstat>
</response>
</multistatus>
```

but `.readdir()` returns empty array.
After quick debugging I found that if remove `d:` prefix in all selectors (see `source/adapter/parse.js:33`) everything works OK.

What are these prefixes for?

**Comment by smolnikov** [comment]
Looks like I'm getting invalid webdav XML, right?
http://www.webdav.org/specs/rfc2518.xml#rfc.section.13.8.1

**Comment by perry-mitchell** [comment]
> Looks like I'm getting invalid webdav XML, right?

@smolnikov It seems that way. What are you using as the server?

I'm not an expert in WebDAV by any measure. The `D:` tags were present in every platform I tried when building the library. If another spec exists I could accommodate that, perhaps.

**Comment by smolnikov** [comment]
@perry-mitchell I'm using webdav to get files from Demandware file storage. Demandware has no public docs for its webdav implementations, unfortunately :(

**Comment by perry-mitchell** [comment]
@smolnikov That's unfortunate. You _could_ potentially make a PR if you wanted to. The code needing changing is in the webdav-client project (for instance: https://github.com/perry-mitchell/webdav-client/blob/master/source/adapter/parse.js#L32)

For instance it would need some kind of formatting function where you'd pass the plain key, and it would return an array of key transformations to try, similar to this: https://github.com/perry-mitchell/webdav-client/blob/master/source/adapter/parse.js#L52

Let me know if you're interested in contributing.

**Comment by smolnikov** [comment]
@perry-mitchell I guess I'm interested, but I'm not an expert both in node.js and WebDAV, so I need to dive deeper into your code before start.

Look, http://www.webdav.org/specs/rfc2518.xml#rfc.section.8.1.3 says that there might be no `d:` prefixes in WebDAV XML response. Not sure about what's the difference between prefixed and non-prefixed tags.

**Comment by perry-mitchell** [comment]
@smolnikov Yeah, there's a small bit of explanation here of how it might look: https://msdn.microsoft.com/en-us/library/ms879496(v=exchg.65).aspx. 

I'm closing this issue in favour of perry-mitchell/webdav-client#24 - let's continue the discussion there, as that's where the implementation will need to be handled.
