### ISSUE TITLE
mkdir does not seem to handle paths with umlauts correctly, possibly applies to other APIs as well.

### ISSUE THREAD

**Issue by ccoenen** [perry-mitchell/webdav-fs#44]
I have this following piece of code, which illustrates my problem. Save this as a utf-8 encoded JavaScript file and run it against a server (In my case it's nextcloud but it should not matter).

```javascript
var wfs = require("webdav-fs")(
	"http://example.com/webdav/", // CHANGE THIS
	"username", // CHANGE THIS
	"password" // CHANGE THIS
);

// FIRST TRY: just pass a string to mkdir
// Console output:
// Error { Error: Bad response: 500
//     at handleResponseError (....node_modules\webdav-fs\source\client.js:31:23)
//     at process._tickCallback (internal/process/next_tick.js:103:7) httpStatusCode: 500 }
// Apache logfile output:
// <ip> - <name> [06/Apr/2017:02:04:51 +0200] "MKCOL /remote.php/webdav/\xe4 HTTP/1.1" 500 0/604679 4741 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wfs.mkdir('/ä', function (err) {
	if (err) {
		console.error("Error", err);
	} else {
		console.log("Just fine");
	}
});


// SECOND TRY: encode it yourself and pass that.
// Console output:
// Just fine
// Apache logfile output:
// <ip> - <name> [06/Apr/2017:02:04:51 +0200] "MKCOL /remote.php/webdav/%C3%B6 HTTP/1.1" 201 0/629212 4556 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
wfs.mkdir('/' + encodeURIComponent('ö'), function (err) {
	if (err) {
		console.error("Error", err);
	} else {
		console.log("Just fine");
	}
});
```

I will end up with one directory, the "ö" (second case), the first one returns with an error 500 and does not create a directory.

This problem may well be in other APIs as well, i did not test that, though.

**Comment by ccoenen** [comment]
it should be noted that just tossing the encoding in there _will_ break subdirectories, this can be demonstrated with these two blocks:

```javascript
// will fail!
wfs.mkdir(encodeURIComponent('ö/test1'), function (err) {
	if (err) {
		console.error("Error", err);
	} else {
		console.log("Just fine");
	}
})
```

```javascript
// this will work, we now have a subdirectory "test2" below "ö".
wfs.mkdir(encodeURIComponent('ö')+'/test2', function (err) { // apache log will say: /remote.php/webdav/\xe4
	if (err) {
		console.error("Error", err);
	} else {
		console.log("Just fine");
	}
})
```

I am not very familiar with the webdav spec, and if this is more or less expected behaviour.

**Comment by ccoenen** [comment]
I was testing with 0.6.0, I'm now rerunning my tests with 1.0.0-rc7

**Comment by perry-mitchell** [comment]
Thanks @ccoenen. So it looks there's some unicode issue here? After a bit of googling it seems that this might be a common issue with webdav.

As we're both using software based on ownCloud (originally), we're probably running SabreDAV under the hood. Found this interesting article on path encoding: http://sabre.io/dav/character-encoding/

Regardless I'll try and replicate this on my system and in the unit tests as soon as I can.

**Comment by ccoenen** [comment]
(from sabredav docs)
> HTTP urls don't specify any encodings, they are just lists of bytes. As a result a client may encode the url http://example.org/üvert as one of the following:
> 
> ```
> http://example.org/%FCvrt // latin-1
> http://example.org/%C3%BCvrt // utf-8 normalization form C
> http://example.org/u%CC%88vrt // utf-8 normalization form D
> ```
> 
> The last three urls are 'identical' for a user, but from a HTTP perspective they are all distinct urls.
> 
> SabreDAV will accept either form and internally encode everything to UTF-8, but we cannot fix bad-behaving clients.

So if the first test were `%E4` instead of `\xe4` it would work? Or is this perhaps another layer of problem obfuscation by the apache logfile? Sadly, I can't capture the actual bytes on the wire, as they are encrypted.

Regardless, I think that sending utf-8 encoded (`ä` being `%C3%A4` instead of `\xE4`) would be preferable. The automatic conversion (that other dav backends may not implement the same way) makes me a little uneasy.

**Comment by ccoenen** [comment]
I found this table, the lower half lists a lot of other umlauts as well, in case you need material for tests:
https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by perry-mitchell** [comment]
Should be solved in perry-mitchell/webdav-client#66

**Comment by ccoenen** [comment]
for mkdir, this has been resolved. I may have found a similar bug in rename, but I'm not sure yet.

**Comment by ccoenen** [comment]
yes, I can confirm that a encodeURIComponent in the target of a `.rename` is also needed when moving a directory to some subdirectory.

**Comment by ccoenen** [comment]
should I create a new issue for this?

**Comment by perry-mitchell** [comment]
Yes please!
