### ISSUE TITLE
"1 vulnerability required manual review and could not be updated"

### ISSUE THREAD

**Issue by moeiscool** [perry-mitchell/webdav-fs#59]
Hello there :D I have a problem with a package vulnerability. When I don't have `webdav-fs` installed I don't get any issues but after installing it tells me i have vulnerabilities.

When i attempt to run
```
npm audit fix
```
it gives me this after installing `webdav-fs`
```
fixed 0 of 1 vulnerability in 1736 scanned packages
  1 vulnerability required manual review and could not be updated
```

Currently running Ubuntu 17.10.1
cpu info : 
```
     *-cpu
          description: CPU
          product: Intel(R) Core(TM) i7 CPU         960  @ 3.20GHz
          bus info: cpu@0
          version: Intel(R) Core(TM) i7 CPU 960 @ 3.20GHz
          capabilities: x86-64 fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm ida cpufreq
```

is there something i can do to fix it? thanks!

**Comment by perry-mitchell** [comment]
Can you post the output of `npm audit`?

The vuln might be in the `webdav` dependency, which I'll update soon, but I've had no issues running `npm audit fix`.

**Comment by perry-mitchell** [comment]
@moeiscool I updated all the deps in 1.11.0.. Could you update to that version? You should notice that all mentioned vulnerabilities are gone.

**Comment by moeiscool** [comment]
ah thank you! time to integrate!!! (Well i already did, now i can test it!!!) thanks again!
