### ISSUE TITLE
createwriteStream binary file

### ISSUE THREAD

**Issue by sbergt** [perry-mitchell/webdav-fs#68]
Hi i want to stream a binary file. (huge file) But is always empty. 

var readStream = fs.createReadStream("./public/files/test.exe");
    readStream.setEncoding('binary');
    readStream.pipe(wfs.createWriteStream("/test.exe"));

**Comment by perry-mitchell** [comment]
Are you doing this in Node? Could you use the [`--inspect` flag](https://nodejs.org/en/docs/guides/debugging-getting-started/#enable-inspector) and check what the network request+response look like?

Also, your path is wrong as it contains a relative path. Paths on WebDAV should be absolute.
