### ISSUE TITLE
Binary file support

### ISSUE THREAD

**Issue by fr-kshibata** [perry-mitchell/webdav-fs#7]
how do you pipe an image file to a webdav server?

**Comment by perry-mitchell** [comment]
Haven't actually tested any binary final transfers. I'll attempt to look at it today.

**Comment by perry-mitchell** [comment]
@fr-kshibata So what do you mean by piping? You can easily write a buffer to a remote file:

```
wfs.writeFile("test.dat", buffer, function(err) {
```

webdav-fs doesn't support streaming etc.

**Comment by puco** [comment]
Is this released already? I tried with Buffer and get an empty file on the server. (using 0.4.0)

```
var data = new Buffer("I'm string!!!", 'utf-8'); //fs.readFileSync('./test.txt'); // also does not work
console.log(data.length);
wfs.writeFile('test.txt', data, (err) => {
  console.log(err);
});
```

**Comment by perry-mitchell** [comment]
@puco 
```
wfs.writeFile("test.txt", data, "binary", (err) => {
    console.log(err);
})
```
