### ISSUE TITLE
Authentication example does not work

### ISSUE THREAD

**Issue by Choppel** [perry-mitchell/webdav-fs#71]
The example states that a connection can be made like this
````
var wfs = require("webdav-fs")(
    "http://example.com/webdav/",
    "username",
    "password"
);
````
But it should be like this (second param needs to be an object; see underlying module https://github.com/perry-mitchell/webdav-client)
````
var wfs = require("webdav-fs")(
    "http://example.com/webdav/",
    {
      "username": "Bob",
      "password": "Belcher"
    }
);
````

**Comment by perry-mitchell** [comment]
I updated the docs, thanks @Choppel
