### ISSUE TITLE
Hello there :D I have a problem with a package vulnerability.

### ISSUE THREAD

**Issue by MohamedAhmed122** [perry-mitchell/webdav-fs#78]

**Comment by MohamedAhmed122** [comment]
I was trying to install some packages to my react project, and I got this " found 1 low severity vulnerability"  so I did run `npm audit` and I found the problem in react-scripts dependencies, so I ran npm install `react-scripts --save

`, but that didn't solve the problem and still have the same error " found 1 low severity vulnerability"
and i also ran `npm audit fix` and this was the result
fixed 0 of 1 vulnerability in 931989 scanned packages
  1 vulnerability required manual review and could not be updated
![Uploading c2dd581b-c5d2-4156-8229-28bb4d809685.png…](here is my terminal which describes my error clearly)

**Comment by perry-mitchell** [comment]
@MohamedAhmed122 I don't see anything in that screenshot related to this library.
