### ISSUE TITLE
Cannot find package

### ISSUE THREAD

**Issue by griffi-gh** [perry-mitchell/webdav-fs#82]
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '...\node_modules\webdav-fs\' imported from ...\index.js

←[90m    at new NodeError (node:internal/errors:371:5)←[39m
←[90m    at legacyMainResolve (node:internal/modules/esm/resolve:308:9)←[39m
←[90m    at packageResolve (node:internal/modules/esm/resolve:812:14)←[39m
←[90m    at moduleResolve (node:internal/modules/esm/resolve:864:18)←[39m
←[90m    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:978:11)←[39m
←[90m    at Loader.resolve (node:internal/modules/esm/loader:89:40)←[39m
←[90m    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)←[39m
←[90m    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)←[39m
←[90m    at link (node:internal/modules/esm/module_job:75:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m

After upgrading to v4
There's no "source" directory, only dist and package.json points to it

**Comment by perry-mitchell** [comment]
It works fine for me on node 14, and in typescript. What setup are you using?

Dist is the built copy, source is not shipped on npm. This is correct.

**Comment by griffi-gh** [comment]
I just installed the package with
`npm i webdav-fs --save`
package.json points to the files in the "source" directory. Changing it to "dist" makes it work properly

**Comment by perry-mitchell** [comment]
@griffi-gh You're right, sorry, it seems I never updated the package.json reference. Thanks for posting, I'll patch this right away.

**Comment by perry-mitchell** [comment]
Fix released in 4.0.1
