### ISSUE TITLE
Can I use this library in not node.js environment?

### ISSUE THREAD

**Issue by sytolk** [perry-mitchell/webdav-fs#88]
I have use webdav-fs library in Electron renderer process without nodeIntegration. And have error that node.js `stream` is missing in `node_modules/webdav/dist/node/operations/putFileContents.js` but actually webdav package have browser support: https://github.com/perry-mitchell/webdav-client#browser-support 
With node-polyfill-webpack-plugin it works but is not option for me.. (it polyfill process too).
The question: Is it possible to switch from Node.js to browser support in webdav-fs library too?

**Comment by perry-mitchell** [comment]
I'd recommend using [`webdav`](https://github.com/perry-mitchell/webdav-client) instead, the core library, as it's designed to also work in the browser.
