### ISSUE TITLE
Replace 'request' package for browserify

### ISSUE THREAD

**Issue by perry-mitchell** [perry-mitchell/webdav-fs#9]
'request' doesn't work so well with browserify, which is required downstream. Use node-fetch instead: https://www.npmjs.com/package/node-fetch

**Comment by puco** [comment]
I think with the introduction of *node-fetch* the binary file download is broken. I can't specify any encoding that we give me an unmodified file than on the server. (But same looks for 0.3.3 with request)

**Comment by perry-mitchell** [comment]
Hmm.. We've got tests covering this. Have you tried the following?

```
wfs.readFile("/bin.dat", "binary", function(err, contents) {
```

`readFile` allows for specifying an encoding.

I do need to improve documentation - my apologies.
